### PR TITLE
Add stylelint for CSS linting

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by pdehaan** [comment]
Current status is about 8 errors (after autofixing via `--fix` flag):

```sh
npm run lint-css -- --fix

> svelte-app@1.0.0 lint-css /Volumes/Dev/github/mozilla/ion-core-addon
> stylelint 'public/*.css' '.storybook/*.css' 'src/**/*.svelte' 'stories/**/*.svelte' "--fix"


public/common.css
 146:1  ✖  Unexpected duplicate selector ":root", first used at line 8                  no-duplicate-selectors
 735:1  ✖  Unexpected duplicate selector "xul|search-textbox", first used at line 343   no-duplicate-selectors
 748:1  ✖  Unexpected duplicate selector "html|button", first used at line 175          no-duplicate-selectors

public/global.css
 24:3  ✖  Unexpected duplicate "align-items"                                declaration-block-no-duplicate-properties
 50:1  ✖  Unexpected duplicate selector "#summary", first used at line 50   no-duplicate-selectors                   

public/rally.css
 56:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword

src/components/Accordion.svelte
 57:3  ✖  Unexpected duplicate selector ".carat", first used at line 53   no-duplicate-selectors

src/routes/terms-of-service/Content.svelte
 29:18  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword
```

**Comment by Dexterp37** [comment]
@hamilton what's your take on this?

**Review by hamilton — CHANGES_REQUESTED** [review]
Thank you @pdehaan! This looks great. I've filed a follow-on PR to perform the css linting on the repository that is built off of this branch. I had one small change; once that is in, we can mrege this and I'll rebase my branch.

**Comment by pdehaan** [comment]
Updated and rebased. CI failure is expected and addressed in #127.

**Review by hamilton — APPROVED** [review]
Thanks for the PR @pdehaan.

**Pull request merged**
