### PR TITLE
Add recommendation file, suppress install warning

### LINKED ISSUE #159: Provide a signed version of the Core Addon; potentially enable “Badging" (CA-P0, CA-P1)
Provide a signed version of the Core Addon
- And potentially enable “Badging"

### PR DESCRIPTION
**Pull request by rhelmer**
See issue #195, closes #159. This implements "add-on badges",
which also removes the warning prompt when starting an install
from an untrusted origin. See https://blog.mozilla.org/addons/2020/10/05/new-add-on-badges/

### CODE REVIEW

**Comment by rhelmer** [comment]
Note that I haven't actually tested this yet, I could use help doing so :) From reading the addons manager code I don't think temporarily-installed is good enough, disabling signature checks might be. Using dev-root should be (but this requires us to have our tasckluster CI wired up which we're working on elsewhere)

**Comment by Dexterp37** [comment]
@rhelmer I believe some Add-on peer should review this code. Also note that web-ext linting is calling this out as an error, too :)

**Comment by Dexterp37** [comment]
@rhelmer can this be closed?

**Comment by rhelmer** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1681331 just landed on Nightly which suppresses this prompt for privileged extensions, I don't think we need to figure out recommendation badges for the privileged signing infra right now.

**Pull request closed without merging**
